bnb-chain/greenfield-contracts

- foundry-scripts/GroupHub.s.sol
- foundry-scripts/updateGroup.sh
This PR adds the script to add member to a group.
The script is for a demo.
None
Just script
> feat: add addMembers foundry script

- Makefile
- contracts/CrossChain.sol
- contracts/Deployer.sol
- contracts/RelayerHub.sol
- contracts/interface/IAccessControl.sol
- contracts/interface/IBucketHub.sol
- contracts/interface/ICmnHub.sol
- contracts/interface/IGroupHub.sol
- contracts/interface/IMiddleLayer.sol
- contracts/interface/IObjectHub.sol
- contracts/middle-layer/GovHub.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/CmnHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/ObjectHub.sol
- contracts/middle-layer/resource-mirror/utils/AccessControl.sol
- foundry-scripts/GroupHub.s.sol
- foundry-scripts/updateGroup.sh
- package.json
- scripts/1-deploy.ts
- yarn.lock
resolve issues from audit report
* fix(CrossChain-L01): remove redundant if statement
* fix(Deployer-I01): fix short circuit the transaction as early as possible
* fix(RelayerHub-L01): strict receiving BNB funds
* fix(GovHub-L01): remove unused error message
* fix(ObjectHub-M01): make contracts extend interfaces
> fix(audit): resolve issues from audit report

- contracts/interface/IGroupHub.sol
- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/rlp/GroupRlp.sol
- contracts/middle-layer/resource-mirror/storage/GroupStorage.sol
- foundry-scripts/Dev.s.sol
- foundry-scripts/GroupHub.s.sol
- foundry-tests/GroupHub.t.sol
This pr is to add a new field(`extra`) for group resource
* add `extra` to `CreateGroupSynPackage` and `UpdateGroupSynPackage`
* other related changes
> feat: add extra field for group resource

- foundry-scripts/GroupHub.s.sol
fix update group call error in the foundry script
* fix update group call error in the foundry script
* ...
> fix: update group call error in the foundry script

- .github/workflows/publish-npm.yml
- package.json
This pr is to add npm publish workflow
* add npm publish workflow
> chore: add npm publish workflow

- .github/workflows/unit-test.yml
- package.json
Resolve issue that ci action occasionally fails
> feat: modify ci

- package.json
> fix: update npm publish version

- package.json
update invalid publish version
> fix: update invalid publish version

- package.json
update npm publish version to 0.0.9-alpha4
> feat: update npm publish version

- .env.example
- .github/workflows/unit-test.yml
- README.md
- contracts/Config.sol
- contracts/CrossChain.sol
- contracts/GnfdLightClient.sol
- contracts/RelayerHub.sol
- contracts/interface/ITokenHub.sol
- contracts/middle-layer/GovHub.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/CmnHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/test/GnfdLightClientTest.sol
- foundry-tests/RelayerHub.t.sol
- foundry-tests/TokenHub.t.sol
- package.json
- scripts/1-deploy.ts
- scripts/6-claim-unlock-bot.ts
- yarn.lock
set upper limit of relayFee to 1 BNB and add timelock for large cross-chain transfers 
for cross-chain safety
* set upper limit of relayFee and ackRelayFee to 1 BNB
* add timelock for large cross-chain transfers 
* add auto claim unlock bot
* modify tests
* update npm publish version
> feat: set upper limit of relayFee to 1 BNB and add timelock for large cross-chain transfers 

- package.json
update npm publish version to 0.0.9
* update npm publish version to 0.0.9
* ...
> feat: update npm publish version to 0.0.9

- contracts/GnfdLightClient.sol
- contracts/test/GnfdLightClientTest.sol
shorten the inturn relayer timeout to 30s
* shorten the inturn relayer timeout
* ...
> feat: shorten the inturn relayer timeout (#65)

- package.json
update npm publish version to 0.1.0
* update npm publish version to 0.1.0
* ...
> feat: update npm publish version to 0.1.0

- package.json
update npm publish version to 0.1.0
* update npm publish version to 0.1.0
* ...
> feat: update npm publish version to 0.1.0 (#70)

- README.md
Update the contract entry point of testnet
None
None
None
> docs: update the contract enrtypoint of testnet

- README.md
update the contract point of testnet
None
None
None
> docs: update the contract point of testnet (#73)

- contracts/GnfdLightClient.sol
recover validatorSetChanged after precompile contract bug fixed
*  recover validatorSetChanged after precompile contract bug fixed
* ...
> fix: recover validatorSetChanged after precompile contract bug fixed

- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/storage/GroupStorage.sol
- foundry-scripts/GroupHub.s.sol
- foundry-tests/GroupHub.t.sol
This PR is to adapt to the GroupMember Expiration feature.
add an example CLI or API response...
* GroupHub
> feat: add group member expiration

- package.json
update npm publish version to 0.1.1-alpha1
* update npm publish version to 0.1.1-alpha1
* ...
> feat: update npm publish version to 0.1.1-alpha1

- package.json
update npm publish version (#76)
* update npm publish version (#76)
* ...
> feat: update npm publish version (#76)

- contracts/CrossChain.sol
- foundry-tests/CrossChain.t.sol
- foundry-tests/TokenHub.t.sol
Change the default relayer to break even the actual relayer fee
None
None
> feat: change the defualt ack relayer fee

- contracts/middle-layer/GovHub.sol
- foundry-scripts/EmergencyOperator.s.sol
- foundry-scripts/examples/emergencyOperator.sh
- hardhat.config.ts
- scripts/2-verify-scan.ts
- scripts/7-deploy-implements-for-upgrade.ts
add upgrade script for emergency operator and more check in GovHub
* add script to deploy new implements for upgrades
* add more check while upgrading contracts in GovHub contract
* ...
> feat: add upgrade script for emergency operator and more check in GovHub

- contracts/Config.sol
- contracts/middle-layer/GovHub.sol
- foundry-tests/GovHub.t.sol
- scripts/1-deploy.ts
- scripts/2-verify-scan.ts
- scripts/7-deploy-implements-for-upgrade.ts
add Emergency Upgrade Operator
* add emergencyUpgradeOperator for emergency update/upgrade
* set emergencyOperator only for emergencySuspend/Reopen/CancelTransfer
* ...
> feat: add Emergency Upgrade Operator

- package.json
- scripts/7-deploy-implements-for-upgrade.ts
update npm publish version and modify upgrade script
for new release
* update npm publish version 
* optimize upgrade script
* ...
> feat: update npm publish version and modify upgrade script

- contracts/Config.sol
optimize config contract, saving code size
save code size 
* make configSlots to private
* ...
> feat: optimize config contract, saving code size

- contracts/Config.sol
- contracts/CrossChain.sol
- contracts/middle-layer/GovHub.sol
- contracts/test/GnfdLightClientTest.sol
- foundry-scripts/EmergencyOperator.s.sol
- foundry-scripts/examples/emergencyOperator.sh
- foundry-tests/CrossChain.t.sol
- foundry-tests/GovHub.t.sol
- foundry-tests/TokenHub.t.sol
- hardhat.config.ts
- package.json
- scripts/1-deploy.ts
- scripts/2-verify-scan.ts
- scripts/7-deploy-implements-for-upgrade.ts
add emergency operator for GovHub and change the default ack relay fee
* add emergency operator for GovHub
* change the default ack relay fee
* ...
> feat: add emergency operator for GovHub and change the default ack relay fee

- contracts/GnfdLightClient.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/AdditionalBucketHub.sol
- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/AdditionalObjectHub.sol
- contracts/middle-layer/resource-mirror/storage/BucketStorage.sol
- contracts/middle-layer/resource-mirror/storage/CmnStorage.sol
- contracts/middle-layer/resource-mirror/storage/GroupStorage.sol
- contracts/middle-layer/resource-mirror/storage/ObjectStorage.sol
- contracts/middle-layer/resource-mirror/storage/PackageQueue.sol
- contracts/middle-layer/resource-mirror/utils/GnfdAccessControl.sol
> fix: audit reports

- package.json
feat: update npm publish version to 0.1.1-alpha3
* update npm publish version to 0.1.1-alpha3
* ...
> feat: update npm publish version to 0.1.1-alpha3

- contracts/GnfdLightClient.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/AdditionalBucketHub.sol
- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/AdditionalObjectHub.sol
- contracts/middle-layer/resource-mirror/storage/BucketStorage.sol
- contracts/middle-layer/resource-mirror/storage/CmnStorage.sol
- contracts/middle-layer/resource-mirror/storage/GroupStorage.sol
- contracts/middle-layer/resource-mirror/storage/ObjectStorage.sol
- contracts/middle-layer/resource-mirror/storage/PackageQueue.sol
- contracts/middle-layer/resource-mirror/utils/GnfdAccessControl.sol
- package.json
* fix: rename RewardTo event to TransferTo event
* fix: add onlyCrossChain check in verifyRelayerAndPackage
* fix: adjust storage
* fix errors
> fix: audit reports (#86)

- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/storage/GroupStorage.sol
This pr is to fix typo within `UpdateGroupOpType`
* no notable changes
> fix: typo of `UpdateGroupOpType`

- Makefile
- package.json
- yarn.lock
update openzeppelin version to latest
for safety
> feat: update openzeppelin version

- Makefile
- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/CmnHub.sol
- contracts/middle-layer/resource-mirror/storage/GroupStorage.sol
- package.json
- yarn.lock
update openzeppelin version to latest, fix typo
> feat: update openzeppelin version to latest, fix typo

- package.json
This pr is to update npm version to prepare for new release v0.1.1
* update npm version
> release: prepare for new release v0.1.1

- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/CmnHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/ObjectHub.sol
add more check to `updateGroup`
* fix: add more check to `updateGroup`
* remove check for duplicate elements
* add support of `AdditionalContract` to `updateParam`
* fix review comment
> fix: add more check to `updateGroup` (#100)

- package.json
update npm publish version to 0.1.2-alpha1
> feat: update npm publish version (#102)

- .github/workflows/lint-pr.yml
- contracts/CrossChain.sol
- contracts/Deployer.sol
- contracts/GnfdLightClient.sol
- contracts/RelayerHub.sol
- contracts/middle-layer/GovHub.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/AdditionalBucketHub.sol
- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/AdditionalObjectHub.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/CmnHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/ObjectHub.sol
- contracts/middle-layer/resource-mirror/storage/CmnStorage.sol
- contracts/middle-layer/resource-mirror/storage/PackageQueue.sol
- foundry-tests/BucketHub.t.sol
- foundry-tests/GnfdLightClient.t.sol
- foundry-tests/GroupHub.t.sol
- foundry-tests/ObjectHub.t.sol
- scripts/7-deploy-implements-for-upgrade.ts
This pr is to fix some issues from audit report
* add more security check
* add `maxCallbackDataLength` to restrict callback data length
* remove `failReason` from `RetryPackage`
* add `_disableInitializers` to implementation contracts
> fix: issues from audit report

- package.json
update npm publish version to 0.1.2
> feat: update npm publish version to 0.1.2

- package.json
update npm publish version to v0.1.3-alpha1
> feat: update npm publish version to v0.1.3-alpha1

- package.json
modify npm publish version to 0.1.3-alpha1
> fix: modify npm publish version to 0.1.3-alpha1

- .github/workflows/lint-pr.yml
- contracts/CrossChain.sol
- contracts/Deployer.sol
- contracts/GnfdLightClient.sol
- contracts/RelayerHub.sol
- contracts/middle-layer/GovHub.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/AdditionalBucketHub.sol
- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/AdditionalObjectHub.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/CmnHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/ObjectHub.sol
- contracts/middle-layer/resource-mirror/storage/CmnStorage.sol
- contracts/middle-layer/resource-mirror/storage/PackageQueue.sol
- foundry-tests/BucketHub.t.sol
- foundry-tests/GnfdLightClient.t.sol
- foundry-tests/GroupHub.t.sol
- foundry-tests/ObjectHub.t.sol
- package.json
- scripts/7-deploy-implements-for-upgrade.ts
* fix: add gas check before `greenfieldCall`
* fix: add `maxCallbackDataLength` to restrict callback data length
* fix: remove `failReason` from `RetryPackage`
* fix: add `_disableInitializers` to implementation contracts
* fix(audit): for 9.Expensive and Non-Standard Deployment, add onlyOperator for deploy method
* fix: modify script for upgrading
* fix(audit): for 5.A Specific Sequence Package Cannot Be Skipped, add emergencyChangeSequence, allow emergencyUpgradeOperator to set sequence plus or minus one
* fix: add initializeV2 on deployer contract, fix value.length check
* chores: lint code
* fix: test init issue
* chores: modify emergencyChangeSequence interface
* chores: rename github token name
* Revert "fix: add gas check before `greenfieldCall`"
This reverts commit …
> fix: issues from audit report (#104)

- contracts/CrossChain.sol
- contracts/GnfdLightClient.sol
- contracts/RelayerHub.sol
- contracts/middle-layer/GovHub.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/ObjectHub.sol
- package.json
update versionInfo for upgrades
> feat: update versionInfo for upgrades

- contracts/CrossChain.sol
- contracts/GnfdLightClient.sol
- contracts/RelayerHub.sol
- contracts/middle-layer/GovHub.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/ObjectHub.sol
- contracts/test/GnfdLightClientTest.sol
- package.json
* feat: update versionInfo
* feat: update npm publish version
> feat: update versionInfo for upgrades (#109)

- package.json
update npm publish version to 0.1.3
> fix: update npm publish version to 0.1.3

- package.json
update npm publish version to 0.1.3
> fix: update npm publish version to 0.1.3 (#111)

- Makefile
- remappings.txt
This pr is to fix the build errors
* remove forge dependencies and modify `remappings.txt`
> fix: build errors

- package.json
update npm publish version to 1.0.0
> feat: update npm publish version to 1.0.0

- Makefile
- package.json
- remappings.txt
modify build errors and update npm publish version to 1.0.0
> feat: modify build errors and update npm publish version to 1.0.0

- contracts/CrossChain.sol
- contracts/Deployer.sol
- foundry-tests/Deployer.t.sol
- scripts/1-deploy.ts
add enableCrossChainTransfer in init params
to support the gnfd contracts deployment on opbnb
> feat: add enableCrossChainTransfer in init params

- contracts/middle-layer/resource-mirror/BucketHub.sol
update BucketHub versionInfo for upgrades
> feat: update BucketHub versionInfo

- contracts/CrossChain.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
modify emergencyChangeSequence to support oracle sequence, lint code
> feat: modify emergencyChangeSequence to support oracle sequence

- contracts/CrossChain.sol
- contracts/Deployer.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/storage/BucketStorage.sol
- foundry-scripts/BucketHub.s.sol
- foundry-tests/BucketHub.t.sol
- foundry-tests/Deployer.t.sol
- scripts/1-deploy.ts
add emergency change sequence for opbnb deployment, fix create group interface
to support the deployment on opbnb
> feat: add emergency change sequence for opbnb deployment, fix create group interface

- .env.example
- hardhat.config.ts
- package.json
- scripts/1-2-deploy-opbnb.ts
- scripts/1-deploy.ts
- scripts/2-verify-scan.ts
- scripts/4-transferOut.ts
- scripts/5-transfer-bnb.ts
- scripts/6-claim-unlock-bot.ts
- scripts/7-deploy-implements-for-upgrade.ts
- scripts/info.ts
add deploy script for opbnb deployment
1. set `OPBNB_RPC`, `OPBNB_PRIVATE_KEY` on `.env`
2. npm run deploy:opbnb
> feat: add deploy script for opbnb

- .env.example
- hardhat.config.ts
- package.json
- scripts/1-2-deploy-opbnb.ts
- scripts/2-verify-scan.ts
- scripts/4-transferOut.ts
- scripts/5-transfer-bnb.ts
- scripts/6-claim-unlock-bot.ts
- scripts/7-deploy-implements-for-upgrade.ts
- scripts/info.ts
add deploy script for opbnb
support deploy on opbnb 
1. set `OPBNB_RPC`, `OPBNB_PRIVATE_KEY` on .env
2. npm run deploy:opbnb
> feat: add deploy script for opbnb (#124)

- .env.example
- hardhat.config.ts
- scripts/1-2-deploy-opbnb.ts
- scripts/2-verify-scan.ts
modify verify script for opbnb deploy
> feat: modify verify script for opbnb deploy

- package.json
update npm publish version to v1.1.0
> feat: update npm publish version to v1.1.0

- scripts/1-2-deploy-opbnb.ts
modify deploy script for opbnb
> chore: modify deploy script for opbnb

- .env.example
- hardhat.config.ts
- package.json
- scripts/1-2-deploy-opbnb.ts
- scripts/2-verify-scan.ts
update npm publish version and fix verify script
> feat: update npm publish version and fix verify script

- package.json
update npm publish version to 1.2.0
* update npm publish version to 1.2.0
* ...
> feat: update npm publish version to 1.2.0

- package.json
update npm publish version (#137)
* update npm publish version 
* ...
> feat: update npm publish version (#137)

- contracts/interface/ICrossChain.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/ObjectHub.sol
- contracts/middle-layer/resource-mirror/PermissionHub.sol
- package.json
- scripts/9-upgrade-multiMessage-gnfdExecutor.ts
modify upgrade version, npm publish version and add multi-message upgrade script
* modify upgrade version and npm publish version
* add multi-message upgrade script
> feat: modify upgrade version and npm publish version

- contracts/CrossChain.sol
- contracts/MultiMessageDeployer.sol
- contracts/middle-layer/GreenfieldExecutor.sol
- contracts/middle-layer/resource-mirror/MultiMessage.sol
- package.json
update upgrade version for CrossChain and add MultiMessageDeployer
* update upgrade version for CrossChain 
* add MultiMessageDeployer
> feat: update upgrade version for CrossChain and add MultiMessageDeployer

- .github/workflows/unit-test.yml
- contracts/Config.sol
- contracts/interface/IERC2771Forwarder.sol
- contracts/interface/ITrustedForwarder.sol
- contracts/middle-layer/GreenfieldExecutor.sol
- contracts/middle-layer/TokenHub.sol
- contracts/middle-layer/resource-mirror/AdditionalBucketHub.sol
- contracts/middle-layer/resource-mirror/AdditionalGroupHub.sol
- contracts/middle-layer/resource-mirror/AdditionalObjectHub.sol
- contracts/middle-layer/resource-mirror/AdditionalPermissionHub.sol
- contracts/middle-layer/resource-mirror/BucketHub.sol
- contracts/middle-layer/resource-mirror/GroupHub.sol
- contracts/middle-layer/resource-mirror/MultiMessage.sol
- contracts/middle-layer/resource-mirror/ObjectHub.sol
- contracts/middle-layer/resource-mirror/PermissionHub.sol
- contracts/middle-layer/resource-mirror/storage/PermissionStorage.sol
- foundry-tests/TrustedForwarder.t.sol
- scripts/8-deploy-permissionHub.ts
- scripts/9-upgrade-multiMessage-gnfdExecutor.ts
add erc2771Forwarder support  for GroupHub, BucketHub, ObjectHub, PermissionHub, TokenHub, MultiMessage and GreenfieldExecutor
* add erc2771Forwarder support  for GroupHub, BucketHub, ObjectHub, PermissionHub, TokenHub, MultiMessage and GreenfieldExecutor
* add IERC2771Forwarder interface
> feat: support ERC2771Forwarder 

- contracts/Config.sol
update erc2771 forwarder to mainnet version
* update erc2771 forwarder to mainnet version
* ...
> feat: update erc2771 forwarder to mainnet version

- contracts/Config.sol
add a description of your changes here...
add an example CLI or API response...
* add each change in a bullet point here
* ...
> feat: update erc2771 forwarder to mainnet version (#152)

- scripts/10-upgrade-erc2771forwarder.ts
add upgrade erc2771 script
* add upgrade erc2771 script
* ...
> feat: add upgrade erc2771 script

- scripts/10-upgrade-erc2771forwarder.ts
add a description of your changes here...
add an example CLI or API response...
* add each change in a bullet point here
* ...
> feat: add upgrade erc2771 script (#154)
